In [56]:
import pandas as pd 
import numpy as np

In [57]:
df = pd.read_excel('flight_price.xlsx')

In [58]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [59]:
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [61]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

# FEATURE ENGINERING

In [62]:
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662

In [63]:
# separting the date of journey
df['Date_of_Journey'].str.split('/')[0]

['24', '03', '2019']

In [64]:
df['Date_of_Journey'].str.split('/').str[2]

0        2019
1        2019
2        2019
3        2019
4        2019
         ...
10678    2019
10679    2019
10680    2019
10681    2019
10682    2019
Name: Date_of_Journey, Length: 10683, dtype: object

In [65]:
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['month'] = df['Date_of_Journey'].str.split('/').str[1]
df['year'] = df['Date_of_Journey'].str.split('/').str[2]

In [66]:
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,month,year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  month            10683 non-null  object
 13  year             10683 non-null  object
dtypes: int64(1), object(13)
memory usage: 1.1+ MB

In [68]:
#converting the object into int
df['month'] = df['month'].astype(int)
df['Date'] = df['Date'].astype(int)
df['year'] = df['year'].astype(int)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  month            10683 non-null  int64
 13  year             10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [70]:
df.drop('Date_of_Journey',axis=1,inplace=True)

In [71]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,month,year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019

In [72]:
# splitting the depature into hr n min
df['Dep_Time'].str.split(':')

0        [22, 20]
1        [05, 50]
2        [09, 25]
3        [18, 05]
4        [16, 50]
           ...
10678    [19, 55]
10679    [20, 45]
10680    [08, 20]
10681    [11, 30]
10682    [10, 55]
Name: Dep_Time, Length: 10683, dtype: object

In [73]:
df['Dep_Time'].str.split(':')[0][0]

'22'

In [74]:
df['Dep_Time'].str.split(':').str[1]

0        20
1        50
2        25
3        05
4        50
         ..
10678    55
10679    45
10680    20
10681    30
10682    55
Name: Dep_Time, Length: 10683, dtype: object

In [75]:
df['Depature_hour'] = df['Dep_Time'].str.split(':').str[0]
df['Depature_min'] = df['Dep_Time'].str.split(':').str[1]

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  month            10683 non-null  int64
 12  year             10683 non-null  int64
 13  Depature_hour    10683 non-null  object
 14  Depature_min     10683 non-null  object
dtypes: int64(4), object(11)
memory usage: 1.2+ MB

In [77]:
df['Depature_hour'] = df['Depature_hour'].astype(int)
df['Depature_min'] = df['Depature_min'].astype(int)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  month            10683 non-null  int64
 12  year             10683 non-null  int64
 13  Depature_hour    10683 non-null  int64
 14  Depature_min     10683 non-null  int64
dtypes: int64(6), object(9)
memory usage: 1.2+ MB

In [79]:
df.drop('Dep_Time',axis=1,inplace=True)

In [80]:
df.head(2)

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,month,year,Depature_hour,Depature_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50

In [81]:
df['Arrival_Time']

0        01:10 22 Mar
1               13:15
2        04:25 10 Jun
3               23:30
4               21:35
             ...
10678           22:25
10679           23:20
10680           11:20
10681           14:10
10682           19:15
Name: Arrival_Time, Length: 10683, dtype: object

In [82]:
df['Arrival_Time'].apply(lambda x : x.split(' '))

0        [01:10, 22, Mar]
1                 [13:15]
2        [04:25, 10, Jun]
3                 [23:30]
4                 [21:35]
               ...
10678             [22:25]
10679             [23:20]
10680             [11:20]
10681             [14:10]
10682             [19:15]
Name: Arrival_Time, Length: 10683, dtype: object

In [83]:
df['Arrival_Time'].apply(lambda x : x.split(' ')[0])

0        01:10
1        13:15
2        04:25
3        23:30
4        21:35
         ...
10678    22:25
10679    23:20
10680    11:20
10681    14:10
10682    19:15
Name: Arrival_Time, Length: 10683, dtype: object

In [84]:
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x : x.split(' ')[0])

In [85]:
df.head(1)

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,month,year,Depature_hour,Depature_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10,2h 50m,non-stop,No info,3897,24,3,2019,22,20

In [86]:
df['Arrival_hour'] = df['Arrival_Time'].str.split(':').str[0]
df['Arrival_min'] = df['Arrival_Time'].str.split(':').str[1]

In [87]:
df['Arrival_hour'] = df['Arrival_hour'].astype(int)
df['Arrival_min'] = df['Arrival_min'].astype(int)

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Arrival_Time     10683 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  month            10683 non-null  int64
 11  year             10683 non-null  int64
 12  Depature_hour    10683 non-null  int64
 13  Depature_min     10683 non-null  int64
 14  Arrival_hour     10683 non-null  int64
 15  Arrival_min      10683 non-null  int64
dtypes: int64(8), object(8)
memory usage: 1.3+ MB

In [89]:
df.drop('Arrival_Time',axis=1,inplace=True)

In [90]:
df.head(1)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,month,year,Depature_hour,Depature_min,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10

In [91]:
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [92]:
df.drop('Additional_Info',axis=1,inplace=True)

In [93]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [94]:
df[df['Total_Stops'].isna()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Price,Date,month,year,Depature_hour,Depature_min,Arrival_hour,Arrival_min
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,7480,6,5,2019,9,45,9,25

In [95]:
df['Total_Stops'].mode()

0    1 stop
Name: Total_Stops, dtype: object

In [96]:
df['Total_Stops'].mode()[0]

'1 stop'

In [97]:
df['Total_Stops'].map({'non-stop':0, '2 stops':2, '1 stop':1, '3 stops':3, np.nan:1 , '4 stops':4})

0        0
1        2
2        2
3        1
4        1
        ..
10678    0
10679    0
10680    0
10681    0
10682    2
Name: Total_Stops, Length: 10683, dtype: int64

In [98]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0, '2 stops':2, '1 stop':1, '3 stops':3, np.nan:1 , '4 stops':4})

In [99]:
df.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Price,Date,month,year,Depature_hour,Depature_min,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,7662,1,5,2019,5,50,13,15

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Airline        10683 non-null  object
 1   Source         10683 non-null  object
 2   Destination    10683 non-null  object
 3   Route          10682 non-null  object
 4   Duration       10683 non-null  object
 5   Total_Stops    10683 non-null  int64
 6   Price          10683 non-null  int64
 7   Date           10683 non-null  int64
 8   month          10683 non-null  int64
 9   year           10683 non-null  int64
 10  Depature_hour  10683 non-null  int64
 11  Depature_min   10683 non-null  int64
 12  Arrival_hour   10683 non-null  int64
 13  Arrival_min    10683 non-null  int64
dtypes: int64(9), object(5)
memory usage: 1.1+ MB

In [101]:
df.drop('Route',axis=1,inplace=True)

In [102]:
df.head(2)

,Airline,Source,Destination,Duration,Total_Stops,Price,Date,month,year,Depature_hour,Depature_min,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,2h 50m,0,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,7h 25m,2,7662,1,5,2019,5,50,13,15

In [103]:
df['Duration_hour'] = df['Duration'].str.split(' ').str[0].str.split('h').str[0]

In [104]:
df['Duration_min'] =df['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [105]:
df.drop('Duration',axis=1,inplace=True)

In [106]:
df.head(2)

,Airline,Source,Destination,Total_Stops,Price,Date,month,year,Depature_hour,Depature_min,Arrival_hour,Arrival_min,Duration_hour,Duration_min
0,IndiGo,Banglore,New Delhi,0,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,2,7662,1,5,2019,5,50,13,15,7,25

In [107]:
from sklearn.preprocessing import OneHotEncoder
encoded = OneHotEncoder()

In [108]:
encoded_data = encoded.fit_transform([['Airline','Source','Destination']]).toarray()

In [109]:
encoded_data

array([[1., 1., 1.]])

In [110]:
encode_df = pd.DataFrame(encoded_data,columns=encoded.get_feature_names_out())

In [111]:
final_df = pd.concat([df,encode_df],axis=1)

In [112]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Price,Date,month,year,Depature_hour,Depature_min,Arrival_hour,Arrival_min,Duration_hour,Duration_min,x0_Airline,x1_Source,x2_Destination
0,IndiGo,Banglore,New Delhi,0,3897,24,3,2019,22,20,1,10,2,50,1.0,1.0,1.0
1,Air India,Kolkata,Banglore,2,7662,1,5,2019,5,50,13,15,7,25,NaN,NaN,NaN
2,Jet Airways,Delhi,Cochin,2,13882,9,6,2019,9,25,4,25,19,NaN,NaN,NaN,NaN
3,IndiGo,Kolkata,Banglore,1,6218,12,5,2019,18,5,23,30,5,25,NaN,NaN,NaN
4,IndiGo,Banglore,New Delhi,1,13302,1,3,2019,16,50,21,35,4,45,NaN,NaN,NaN

In [113]:
final_df['x0_Airline'].unique()

array([ 1., nan])

In [114]:
final_df['x0_Airline'].isna().sum()

np.int64(10682)